spring.application.name=LoggingConcept
server.port=8081
#logging.level.com.telusko.rest = debug
#loging.level.com.telusko.service = trace

logging.level.root  = trace
logging.pattern.console = %c : %p --> %m : : %d %n
logging.file.name = logger/log.txt