spring.application.name=touristapp-global-EH
spring.datasource.url=jdbc:mysql://localhost:3306/teluskodb

spring.datasource.username=root

spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update


spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

spring.jpa.show-sql=true

server.port=8484
